// Production build; synthetic child/parent fixtures, no real account writes.
const {chromium}=require('playwright-core');const http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
(async()=>{
 const root=path.resolve(__dirname,'../schul_cockpit/frontend/dist');
 const server=http.createServer((req,res)=>{let file=path.join(root,req.url.split('?')[0]==='/'?'index.html':req.url.split('?')[0]);try{res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(4179,'127.0.0.1',r));
 const browser=await chromium.launch({executablePath:process.env.SCHOOL_TEST_CHROMIUM,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--no-zygote']});
 const page=await browser.newPage({viewport:{width:390,height:844},serviceWorkers:'block'});const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message);});page.setDefaultTimeout(8000);let reminder={enabled:false,remind_at:null,devices:0},reminderWrites=0;let parent=false,created=false,published=false,sessionBody=null,deleted=false,failDelete=true;
 const tasks=Array.from({length:3},(_,i)=>({prompt:'Eine vollständig sichtbare Aufgabe. '.repeat(30)+`ENDE ${i}`,solution:'Nur in der Elternprüfung sichtbar',criteria:'Begründung',skill_title:'Stromkreis',points:4,minutes:5}));
 const exam=()=>({id:5,title:'Physik üben',subject:'Physik',minutes:15,status:published?'published':'draft',scope:{topics:['Stromkreis'],confirmed:false},tasks});
 await page.route('**/api/**',async route=>{const req=route.request(),u=new URL(req.url()).pathname;let body={},status=200;
 if(u==='/api/me')body={accounts:[{id:1,name:'Beispielkind'}],role:parent?'parent':'child',is_admin:false};
 else if(u.endsWith('/reminders')){if(req.method()==='PUT'){reminder=req.postDataJSON();reminderWrites++;}body={...reminder,can_manage:parent,devices:0};}
 else if(u.endsWith('/rewards'))body={streak:{current:0,record:0},week:[],total:0,start:'2026-09-01',bonus_until:'17:00',badges:[],special:[],medals:[{year:'2026/27',medal:null,pct:0,running:true,limits:[50,65,80]}]};
 else if(u==='/api/parent-report')body={weekday:6,at:'18:00',targets:[],devices:[]};
 else if(u.endsWith('/settings'))body={default_daily_budget_minutes:60,budget_overrides:{},auto_budget:false,erlass:{}};
 else if(u.endsWith('/mentor'))body={profile:{ai_enabled:true},can_manage:parent,can_write:true,subjects:['Physik','Politik'],errors:[],sessions:[],progress:[],homework_choices:[{id:1,subject:'Physik',title:'Vorbereitung auf den Test'}],shared_plan:{goals:[{key:'future',subject:'Politik',title:'Demokratie verstehen',minutes:8,url:'#/learning?goal=future'}],today:{actions:[],planned_minutes:0},week:[],deferred:[]},budget:{opening_confirmed:true,used_eur:0,limit_eur:50,rate_available:true},enabled:true};
 else if(u.endsWith('/sessions/1')){if(req.method()==='DELETE'){if(failDelete){status=500;body={detail:'Löschen nicht gespeichert'};}else{deleted=true;body={ok:true};}}else body={id:1,version:3,subject:'Mathematik',goal:'Gemeinsame Übung',status:'completed',messages:[],summary:'Gespeichert'};}
 else if(u.endsWith('/sessions')&&req.method()==='POST'){sessionBody=req.postDataJSON();body={id:1,subject:sessionBody.subject,goal:sessionBody.goal,status:'completed',messages:[],summary:'Gespeichert'};}
 else if(u.endsWith('/exams')&&req.method()==='POST'){created=true;body={id:5};}
 else if(u.endsWith('/exams'))body={exams:parent||created?[exam()]:[],attempts:[]};
 else if(u.endsWith('/review'))body=exam();
 else if(u.endsWith('/publish')){published=true;body={ok:true};}
 else if(u.endsWith('/start'))body={id:8,version:0,status:'active',exam:{...exam(),tasks:tasks.map(({solution,...t})=>t)},answers:{},feedback:{}};
 else if(u.endsWith('/photos'))body=[];
 await route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});
 });
 await page.goto('http://127.0.0.1:4179/#/learning');await page.getByRole('heading',{name:'Was möchtest du üben?',exact:true}).waitFor().catch(async e=>{console.log(await page.locator('body').innerText());throw e;});
 assert.equal(await page.locator('details .free-choice').count(),0);
 if(process.env.SCHOOL_SCREENSHOT_DIR){await page.setViewportSize({width:768,height:1000});await page.screenshot({path:path.join(process.env.SCHOOL_SCREENSHOT_DIR,'learning-redesign.png'),fullPage:true});}
 await page.getByRole('button',{name:/Demokratie verstehen/}).click();await page.getByRole('button',{name:'Zur Übersicht',exact:true}).waitFor();assert.equal(sessionBody.goal_key,'future');assert.equal(sessionBody.voluntary,true);await page.getByRole('button',{name:'Zur Übersicht',exact:true}).click();
 await page.getByLabel(/^Fach/).selectOption('Politik');await page.getByLabel('Worum geht es ungefähr?').fill('Demokratie');await page.getByRole('button',{name:'Üben starten',exact:true}).click();await page.getByRole('button',{name:'Zur Übersicht',exact:true}).waitFor();assert.equal(sessionBody.subject,'Politik');assert.equal(sessionBody.voluntary,true);
 await page.getByRole('button',{name:'Zur Übersicht',exact:true}).click();assert.equal(await page.getByRole('heading',{name:'Für deine Aufgaben üben'}).count(),0);await page.getByLabel(/^Fach/).selectOption('Physik');await page.getByRole('button',{name:'Übungstest erstellen',exact:true}).click();
 await page.getByRole('heading',{name:'Übungstest zusammenstellen'}).waitFor();assert.equal(await page.getByLabel(/^Fach/).inputValue(),'Physik');
 await page.getByLabel('Eigene Themen (auch ohne automatische Vorschläge)').fill('Stromkreis');await page.getByLabel(/^Dauer/).selectOption('15');await page.getByRole('button',{name:'Übungstest erstellen und starten',exact:true}).click();await page.getByLabel('Deine Antwort',{exact:true}).waitFor();assert(created);assert.equal(await page.getByText('Nur in der Elternprüfung sichtbar',{exact:true}).count(),0);
 await page.goto('http://127.0.0.1:4179/#/learning?help=42');await page.reload();await page.getByRole('button',{name:'Zur Übersicht',exact:true}).waitFor();assert.equal(sessionBody.homework_task_id,42);
 parent=true;await page.goto('http://127.0.0.1:4179/#/learning');await page.reload();await page.getByRole('button',{name:'Übungsklausur',exact:true}).click();await page.getByText(/Entwurf · für das Kind noch nicht sichtbar/).waitFor();await page.getByRole('button',{name:'Aufgaben ansehen und freigeben',exact:true}).click();
 await page.getByRole('button',{name:'Aufgaben bearbeiten',exact:true}).waitFor();assert.equal(await page.locator('textarea').count(),0);assert.equal(await page.getByText(/ENDE 2/).count(),1);
 await page.getByLabel('Ich habe Aufgaben, Lösungen, Umfang und Punkte geprüft.').check();await page.getByRole('button',{name:'Für das Kind freigeben (Echtdaten)',exact:true}).click();await page.getByRole('button',{name:'Aufgaben ansehen und freigeben',exact:true}).waitFor();assert(published);
 for(const width of [320,390,768]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'overflow '+width);}
 await page.goto('http://127.0.0.1:4179/#/learning?session=1');await page.reload();await page.getByRole('button',{name:'Diese Einheit entfernen',exact:true}).click();await page.getByRole('button',{name:'Einheit endgültig löschen',exact:true}).click();await page.getByText('Löschen nicht gespeichert',{exact:true}).waitFor();assert.equal(deleted,false);failDelete=false;await page.getByRole('button',{name:'Einheit endgültig löschen',exact:true}).click();await page.getByRole('heading',{name:'Der echte Lernverlauf.',exact:true}).waitFor();assert(deleted);
 // Erinnerungen stellen Eltern unter „Einstellen“ ein; das Kind liest sie unter „Ich“ (D183).
 await page.goto('http://127.0.0.1:4179/#/einstellen');const reminders=page.locator('.reminder-settings');await reminders.getByText('Erinnerungen',{exact:false}).first().waitFor();assert.equal(reminderWrites,0);await reminders.getByLabel('Uhrzeit (Deutschland)').fill('18:00');await reminders.getByLabel('Tägliche Erinnerung einschalten').check();await reminders.getByRole('button',{name:'Speichern',exact:true}).click();await reminders.getByText('Erinnerungszeit gespeichert.',{exact:true}).waitFor();assert.equal(reminder.remind_at,'18:00');assert.equal(reminder.enabled,true);parent=false;await page.goto('http://127.0.0.1:4179/?kind=1#/ich');await page.getByText(/Dein Tagescheck ist um 18:00/).waitFor();assert.equal(await reminders.getByRole('button',{name:'Speichern',exact:true}).count(),0);
 assert.deepEqual(errors,[]);console.log('PASS: visible free subject choice, free test choice without redundant homework practice, child generation without calendar, hidden answers, parent reading and publication, responsive layout');await browser.close();await new Promise(r=>server.close(r));
})().catch(e=>{console.error(e);process.exit(1)});
