<script>
  import {onMount} from 'svelte';
  import {formatShortDate} from './format.js';
  import {api} from './api.js';
  let {accountId,subjects=[],canManage=false,demo=false,initialSubject='',initialTopic='',onBusy=()=>{}}= $props();
  const base=$derived(`/api/accounts/${accountId}/learning/mentor/exams`);
  let data=$state(null),error=$state(''),busy=$state(false),draft=$state(null),attempt=$state(null);
  let subject=$state(''),scope=$state(''),confirmed=$state(false),minutes=$state(45),index=$state(0),answers=$state({}),reviewed=$state(false);
  let editingDraft=$state(false);
  let period=$state('school_year'),fromDate=$state(''),topicPlan=$state(null),topicChoices=$state([]),selfCheck=$state(null);
  const chosenScope=$derived([...topicChoices.filter(g=>g.selected).map(g=>g.title.trim()),...scope.split('\n').map(x=>x.trim()).filter(Boolean)]);
  function clearTopics(){topicPlan=null;topicChoices=[];}
  async function suggest(){clearTopics();topicPlan=await api.post(`${base}/scope`,{subject,demo,period,start_date:period==='custom'?fromDate:null});topicChoices=topicPlan.groups.map(g=>({...g,selected:g.category==='learning'}));}
  let dirty=$state(false),photos=$state([]),photoInput=$state(null);
  async function load(){data=await api.get(`${base}?demo=${demo}`);}
  async function saveDraft(){await api.put(`${base}/${draft.id}`,{title:draft.title,tasks:draft.tasks});reviewed=false;}
  async function act(fn){if(busy)return;busy=true;error='';try{await fn();}catch(e){error=e.message;}finally{busy=false;}}
  $effect(()=>{onBusy(busy||Boolean(attempt&&dirty)||Boolean(draft));});
  async function save(paused=false){if(!attempt || attempt.read_only || attempt.status!=='active')return;const r=await api.put(`${base}/attempts/${attempt.id}`,{version:attempt.version,answers,paused});attempt=r;dirty=false;}
  async function open(r){attempt=r;answers={...r.answers};index=0;photos=await api.get(`${base}/attempts/${r.id}/photos`);}
  async function upload(e){const file=e.target.files?.[0];if(!file)return;await act(async()=>{await save();const form=new FormData();form.append('file',file);await api.post(`${base}/attempts/${attempt.id}/photos/${index}`,form);photos=await api.get(`${base}/attempts/${attempt.id}/photos`);});e.target.value='';}
  async function move(i){await save();index=i;}
  onMount(()=>{subject=initialSubject;act(load);const timer=setInterval(()=>{if(attempt?.status==='active'&&!busy)act(()=>save(document.hidden));},30000);return()=>clearInterval(timer);});
  const task=$derived(attempt?.exam.tasks[index]);
  const feedback=$derived(attempt?.feedback?.[String(index)]);
</script>
{#if error}<p role="alert" class="notice">{error}</p>{/if}
{#if busy}<p role="status">Wird gespeichert oder vorbereitet …</p>{/if}
{#if selfCheck}<section class="card"><h2>Selbstkontrolle: {selfCheck.title}</h2><p>Gehe die Aufgaben im Kopf oder auf Papier durch. Öffne die Lösung erst danach. Hier entstehen keine KI-Punkte und keine Lernnachweise. Das Öffnen der Lösungen wird vermerkt; eine anschließende Bearbeitung zählt als Übung mit bekannter Lösung.</p>{#each selfCheck.tasks as t,i}<h3>Aufgabe {i+1}</h3><p class="preserve">{t.prompt}</p><details><summary>Lösung und Kriterien zur Selbstkontrolle</summary><p class="preserve">{t.solution}</p><p>{t.criteria}</p></details>{/each}<button onclick={()=>selfCheck=null}>Selbstkontrolle schließen</button></section>
{:else if attempt}
  <header>{#if !attempt.read_only}<p>Direkt tippen oder auf Papier lösen und Fotos bei der jeweiligen Aufgabe anhängen. Nach der Abgabe bewertet der Assistent mit Punkten; unklare Antworten werden gekennzeichnet.</p>{/if}{#if attempt.read_only}<p class="notice">Echter Kinderverlauf · nur ansehen. Antworten und Zeitstand werden nicht verändert.</p>{/if}<h2>{attempt.exam.title}</h2><p>{attempt.exam.minutes} Minuten vorgesehen · {attempt.status==='active'?'Prüfungssimulation':'Abgegeben'}</p></header>
  <nav aria-label="Aufgaben">{#each attempt.exam.tasks as t,i}<button class:chosen={i===index} disabled={busy} onclick={()=>act(()=>move(i))}>{i+1}{answers[String(i)]?' ✓':''}</button>{/each}</nav>
  <section class="card"><p class="muted">Aufgabe {index+1} von {attempt.exam.tasks.length} · {task.points} Punkte · etwa {task.minutes} Minuten</p><h3>{task.skill_title}</h3><p class="preserve">{task.prompt}</p>
    {#each photos.filter(p=>p.question_index===index) as p}<p><a href={`./${base.slice(1)}/attempts/${attempt.id}/photos/${p.id}`} target="_blank" rel="noreferrer">Angehängtes Foto öffnen</a></p>{/each}
    {#if attempt.status==='active'&&!attempt.read_only}
      <label>Deine Antwort<textarea rows="8" bind:value={answers[String(index)]} oninput={()=>dirty=true} disabled={busy} placeholder="Schreibe hier. Du kannst auch über das Mikrofon deiner Tastatur diktieren. Du kannst auch auf Papier arbeiten und ein Foto anhängen."></textarea></label>
      <input style="display:none" type="file" accept="image/*" bind:this={photoInput} onchange={upload}/><button disabled={busy||photos.filter(p=>p.question_index===index).length>=2} onclick={()=>photoInput?.click()}>Foto deiner Lösung anhängen</button>
      <p class="muted">Automatisches Speichern alle 30 Sekunden und beim Aufgabenwechsel. {dirty?'Noch nicht gespeichert.':'Stand gespeichert.'}</p>
      <div class="actions"><button disabled={busy} onclick={()=>act(()=>save(true))}>Speichern und Pause</button><button disabled={busy} onclick={()=>act(async()=>{await save(true);attempt=await api.post(`${base}/attempts/${attempt.id}/submit`);})}>Arbeit abgeben</button></div>
    {:else}
      <h4>Deine Antwort</h4><p class="preserve">{answers[String(index)]||'Keine Antwort eingereicht.'}</p>
      {#if attempt.status!=='active'}<details><summary>Lösung und Kriterien</summary><p class="preserve">{task.solution}</p><p>{task.criteria}</p></details>{/if}
      {#if feedback}{#if feedback.solution_seen}<p class="notice">Lösungen waren vor der Abgabe geöffnet · Übung mit bekannter Lösung, kein Nachweis ohne Hilfe.</p>{/if}<h4>{feedback.uncertain?'Bewertung noch unklar':`${feedback.points} von ${task.points} Punkten · KI-Einschätzung`}</h4><p>{feedback.rationale}</p><p><strong>Nächster Schritt:</strong> {feedback.next_step}</p>{/if}
      {#if attempt.status!=='graded'&&!attempt.read_only}<button disabled={busy} onclick={()=>act(async()=>{attempt=await api.post(`${base}/attempts/${attempt.id}/grade-next`);})}>Nächste Aufgabe auswerten ({Object.keys(attempt.feedback).length}/{attempt.exam.tasks.length})</button>{:else if attempt.status==='graded'}<p>Alle Aufgaben ausgewertet. Vergleiche die Themen, bevor du dir eine Übung aussuchst.</p>{/if}
    {/if}
  </section>
  {#if attempt.status==='graded'}<section class="card"><h3>Das große Ganze</h3>{#each attempt.exam.tasks as t,i}<button style="display:block;text-align:left;width:100%;margin:.5rem 0" onclick={()=>index=i}>{t.skill_title}: {attempt.feedback[String(i)]?.uncertain?'noch unklar':`${attempt.feedback[String(i)]?.points} / ${t.points} Punkte`}</button>{/each}<h4>Deine nächsten sinnvollen Schritte</h4><ul>{#each Object.entries(attempt.feedback).sort((a,b)=>(a[1].points/attempt.exam.tasks[Number(a[0])].points)-(b[1].points/attempt.exam.tasks[Number(b[0])].points)).slice(0,3) as [i,f]}<li>{f.next_step}</li>{/each}</ul><p>KI-Einschätzungen zu den Aufgaben, keine Schulnote. Unklare Bewertungen bitte gemeinsam prüfen.</p></section>{/if}
  <button disabled={busy} onclick={()=>act(async()=>{await save(true);attempt=null;await load();})}>Zur Übersicht</button>
{:else if draft}
  <h2>{draft.title}</h2>{#if draft.status==='draft'}<button disabled={busy} onclick={()=>editingDraft=!editingDraft}>{editingDraft?'Leseansicht':'Aufgaben bearbeiten'}</button>{/if}<p>{draft.minutes} Minuten · {draft.scope.confirmed?'Stoffumfang als Lehrkraft-Vorgabe angegeben':'Stoffumfang noch eine Annahme'}</p>
  {#each draft.tasks as t,i}<section class="card"><h3>{i+1}. {t.skill_title} · {t.points} Punkte</h3>{#if draft.status==='draft'&&editingDraft}<label>Aufgabe {i+1}<textarea rows="5" bind:value={t.prompt} oninput={()=>reviewed=false}></textarea></label><details><summary>Lösung und Kriterien prüfen</summary><label>Lösung {i+1}<textarea rows="4" bind:value={t.solution} oninput={()=>reviewed=false}></textarea></label><label>Punktkriterien {i+1}<textarea rows="4" bind:value={t.criteria} oninput={()=>reviewed=false}></textarea></label></details>{:else}<p class="preserve">{t.prompt}</p><details><summary>Lösung und Kriterien prüfen</summary><p class="preserve">{t.solution}</p><p>{t.criteria}</p></details>{/if}</section>{/each}
  {#if draft.status==='draft'}<button disabled={busy} onclick={()=>act(saveDraft)}>Entwurf speichern</button><label class="check"><input type="checkbox" bind:checked={reviewed}/> Ich habe Aufgaben, Lösungen, Umfang und Punkte geprüft.</label>
  <button disabled={busy||!reviewed} onclick={()=>act(async()=>{await api.put(`${base}/${draft.id}`,{title:draft.title,tasks:draft.tasks});await api.post(`${base}/${draft.id}/publish`,{reviewed});draft=null;await load();})}>{demo?'Nur in der Demo freigeben':'Für das Kind freigeben (Echtdaten)'}</button>{/if}<button disabled={busy} onclick={()=>draft=null}>Zurück</button>
{:else}
  <h2>{demo?'Demo-Übungsklausuren':'Für eine Arbeit üben'}</h2>{#if canManage&&!demo}<p class="notice">Hier stehen echte Arbeiten und Kinderantworten. Neue Entwürfe und Freigaben werden im echten Lernbereich gespeichert.</p>{/if}<p>Wähle Fach und Themen selbst. Du brauchst keinen Termin im Kalender.</p>
  {#each data?.exams||[] as exam}<section class="card"><h3>{exam.title}</h3><p>{exam.subject} · {exam.minutes} Minuten · {exam.status==='published'?(exam.scope.child_created&&!exam.scope.parent_reviewed?'KI-Übung · noch nicht von Eltern geprüft':'Freigegeben'):'Entwurf · für das Kind noch nicht sichtbar'}</p><p>{exam.scope.topics.join(' · ')}</p>
    {#if exam.status==='published'&&(!canManage||demo)}<button disabled={busy} onclick={()=>act(async()=>open(await api.post(`${base}/${exam.id}/start`)))}>Online / Foto bearbeiten</button>{/if}
    <a class="print-link" href={`./${base.slice(1)}/${exam.id}/print`} target="_blank" rel="noreferrer">Aufgaben drucken</a>
    {#if !canManage||demo}<button disabled={busy} onclick={()=>act(async()=>{selfCheck=await api.post(`${base}/${exam.id}/self-check`);})}>Selbstkontrolle ohne Punkte</button>{/if}
    {#if canManage}<button disabled={busy} onclick={()=>act(async()=>{draft=await api.get(`${base}/${exam.id}/review`);reviewed=false;editingDraft=false;})}>Aufgaben ansehen und freigeben</button>{/if}
  </section>{:else}<p>Noch keine Übungsklausur vorbereitet.</p>{/each}
  {#if canManage&&!demo}<h3>Bearbeitungen des Kindes</h3>{#each data?.attempts||[] as a}<button class="history" disabled={busy} onclick={()=>act(async()=>open(await api.get(`${base}/attempts/${a.id}`)))}>{data.exams.find(e=>e.id===a.exam_id)?.title||'Übungsklausur'} · {a.status==='active'?'angefangen':a.status==='graded'?'ausgewertet':'abgegeben'} · {formatShortDate(a.started_at.slice(0,10))}</button>{:else}<p>Noch keine Bearbeitungen des Kindes gespeichert.</p>{/each}{/if}
  <section class="card"><h3>Übungstest zusammenstellen</h3>{#if initialTopic}<p class="preserve">Dein Anlass: {initialTopic}</p><p>Wähle unten die Themen, die du dafür üben möchtest.</p>{/if}<form onsubmit={e=>{e.preventDefault();act(async()=>{const r=await api.post(base,{subject,scope:chosenScope,confirmed_scope:confirmed,minutes,demo,scope_plan_id:topicPlan?.plan_id||null,selected_groups:topicChoices.filter(g=>g.selected).map(g=>({group_id:g.id,title:g.title.trim()}))});if(canManage){draft=await api.get(`${base}/${r.id}/review`);reviewed=false;editingDraft=false;}else{await load();await open(await api.post(`${base}/${r.id}/start`));}});}}>
    <label>Fach<select bind:value={subject} required onchange={clearTopics}><option value="">Bitte auswählen</option>{#each [...new Set([...subjects,initialSubject].filter(Boolean))] as s}<option>{s}</option>{/each}</select></label>
    <label>Unterrichtszeitraum<select bind:value={period} onchange={clearTopics}><option value="school_year">Seit Schuljahresbeginn</option><option value="last_exam">Seit der letzten Klausur in diesem Fach</option><option value="custom">Ab einem eigenen Datum</option></select></label>
    {#if period==='custom'}<label>Beginn<input type="date" bind:value={fromDate} onchange={clearTopics}/></label>{/if}
    <button type="button" disabled={busy||!subject||(period==='custom'&&!fromDate)} onclick={()=>act(suggest)}>{demo?'Themen aus Beispielunterricht vorschlagen':'Themen aus Unterricht vorschlagen'}</button>
    <p class="muted">{demo?'Erfundener mehrwöchiger Unterricht für den Funktionstest. Für den echten Stoff oben zu Kinderstand wechseln.':'Alle dokumentierten Stunden und zugehörigen Hausaufgaben im Zeitraum werden gruppiert, auch bei Fehlzeiten.'} Unveränderte Übersichten werden ohne erneuten KI-Aufruf wiederverwendet.</p>
    {#if topicPlan}<p><strong>{topicPlan.lesson_count} beschriebene Stunden</strong> · {formatShortDate(topicPlan.start_date)} bis {formatShortDate(topicPlan.end_date)}{topicPlan.cached?' · gespeicherte Übersicht':''}</p>
    {#each topicPlan.warnings as warning}<p class="notice">{warning}</p>{/each}
    <button type="button" disabled={busy} onclick={()=>topicChoices=topicChoices.map(g=>({...g,selected:g.category==='learning'}))}>Alle Themen auswählen</button>
    {#each topicChoices as g}<section class="topic"><label class="check"><input type="checkbox" bind:checked={g.selected} disabled={busy||(g.category!=='learning'&&g.category!=='context')}/><strong>{g.title}</strong></label>{#if g.category!=='learning'}<p class="notice">{g.category==='organisation'?'Organisatorischer Eintrag – kein Klausurthema.':g.category==='context'?'Im Unterricht behandelt, aber nicht auf der offiziellen Themenliste der Lehrkraft – nur auf Wunsch üben.':'Stoff noch unklar – bitte Originalmaterial oder ein eigenes konkretes Thema ergänzen.'}</p>{/if}<label>Themenbezeichnung ändern<input bind:value={g.title} maxlength="160" disabled={busy}/></label><p>{g.detail}</p><details><summary>Unterricht und Hausaufgaben ({g.sources.length})</summary>{#each g.sources as ref}<p class="preserve"><small>{formatShortDate(ref.date)} · {ref.kind==='homework'?'Hausaufgabe':'Unterricht'}{ref.missed_minutes?' · versäumte Zeit':''}</small><br/>{ref.text}</p>{/each}</details></section>{/each}
    <p class="muted">Alle erkannten Lernbereiche sind zunächst ausgewählt. Organisatorisches und unklare Einträge bleiben sichtbar, werden aber nicht als Prüfungsstoff verwendet. Unterrichtshäufigkeit ist keine zugesicherte Klausurgewichtung.</p>{/if}
    <label>{topicPlan?'Weitere eigene Themen':'Eigene Themen (auch ohne automatische Vorschläge)'}<textarea bind:value={scope} rows="4" placeholder="Ein Thema pro Zeile. Insgesamt höchstens acht Themenbereiche je Arbeit."></textarea></label>
    <p>{chosenScope.length} Themenbereiche ausgewählt. {#if chosenScope.length>8}Bitte die Auswahl auf höchstens acht Bereiche begrenzen oder mehrere Arbeiten erstellen.{/if}</p>
    <label>Dauer<select bind:value={minutes}>{#each [15,30,45,60,90] as n}<option value={n}>{n} Minuten</option>{/each}</select></label>
    <label class="check"><input type="checkbox" bind:checked={confirmed}/> Dieser Stoffumfang entspricht der Vorgabe der Lehrkraft.</label>
    <button disabled={busy||!subject||!chosenScope.length||chosenScope.length>8||minutes<chosenScope.length*3}>{canManage?'Entwurf erstellen':'Übungstest erstellen und starten'}</button>{#if minutes<chosenScope.length*3}<p class="notice">Bitte mehr Zeit wählen: mindestens drei Minuten je Themenbereich.</p>{/if}<p>{canManage?'Prüfe den Entwurf und gib ihn danach für das Kind frei.':'KI-Aufgaben können Fehler enthalten. Die Lösungen bleiben bis zur Abgabe verborgen.'} Die Erstellung kann etwa eine Minute dauern.</p>
  </form></section>
{/if}
<style>
  .print-link{display:inline-block;padding:.7rem;min-height:44px;box-sizing:border-box;color:var(--accent,#247552)}.topic{border-top:1px solid var(--border,#ccc);padding-top:.5rem}input:not([type="checkbox"]){width:100%;box-sizing:border-box;font:inherit;font-size:16px;padding:.65rem;border-radius:8px;border:1px solid var(--border,#ccc);background:var(--bg-card,#fff);color:inherit}
  .card{padding:1rem;background:var(--bg-card,#fff);border:1px solid var(--border,#d8e2dc);border-radius:16px;margin:1rem 0}.preserve{white-space:pre-wrap;overflow-wrap:anywhere}nav,.actions{display:flex;gap:.5rem;flex-wrap:wrap}button,select{min-height:44px;padding:.6rem .9rem;cursor:pointer}button{border-radius:12px;border:1px solid var(--border,#ccc);background:var(--bg-card,#fff);color:inherit}.chosen{background:var(--accent,#247552);color:var(--accent-fg,#fff)}label{display:block;margin:.8rem 0}textarea,select{display:block;width:100%;box-sizing:border-box;font:inherit;font-size:16px;margin-top:.4rem;padding:.7rem;border-radius:10px;border:1px solid var(--border,#ccc);background:var(--bg-card,#fff);color:inherit}.check{display:flex;gap:.5rem;align-items:center}.muted{font-size:.85rem;opacity:.8}.notice{padding:1rem;background:#fff1d0;color:#4c3610}details{margin:1rem 0}summary{cursor:pointer;min-height:44px}button:disabled{opacity:.5}
</style>
